version: '3.8'

services:
  db:
    image: postgres:15
    container_name: efix-alterdata-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: efix-alterdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
