services:
  db:
    image: postgres:16.9-alpine
    #restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: efix-alterdata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
